// <auto-generated />
using System;
using AspireApp1.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireApp1.Web.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20250421131613_AddEndTimeToReservation")]
    partial class AddEndTimeToReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireApp1.Web.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AspireApp1.Web.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 16,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 17,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 18,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 19,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 20,
                            IsAvailable = true
                        });
                });

            modelBuilder.Entity("AspireApp1.Web.Models.Reservation", b =>
                {
                    b.HasOne("AspireApp1.Web.Models.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("AspireApp1.Web.Models.Seat", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
